language: node_js

node_js:
  - 0.12

addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test','llvm-toolchain-precise-3.5' ]
    # for testing node-webkit
    packages: ['g++-4.8', 'xvfb','libasound2','libx11-6','libglib2.0-0','libgtk2.0-0','libatk1.0-0','libgdk-pixbuf2.0-0','libcairo2','libfreetype6','libfontconfig1','libxcomposite1','libasound2','libxdamage1','libxext6','libxfixes3','libnss3','libnspr4','libgconf-2-4','libexpat1','libdbus-1-3','libudev0']

before_install:
- if [[ $(uname -s) == 'Linux' ]]; then
     export CXX="g++-4.8";
  fi;
- npm config set loglevel=error